### ISSUE TITLE
Maintained ? 

### ISSUE THREAD

**Issue by pniederlag** [asyrjasalo/rfdocker#11]
How is the status of this project?

It uses "robotframework" username on docker-hub and as such suggests that it is somehow officialy related with the robotframework

On the other hand it seems unmaintained and is not mentioned in the official documentation https://hub.docker.com/u/robotframework

So maybe it might be wise do discontinue the project and set it to maintenance mode.

**Comment by asyrjasalo** [comment]
Hi,

We are recruiting maintainers. Kindly apply at opensource@syrjasalo.com.

BR,
  Anssi
