### ISSUE TITLE
Docker tag 'latest'

### ISSUE THREAD

**Issue by Brian-Williams** [asyrjasalo/rfdocker#3]
Could we add a `latest` docker tag for rfdocker image?

**Comment by asyrjasalo** [comment]
Done in https://github.com/asyrjasalo/rfdocker/commit/0bf967e0d36c3e42ae59a2c4a8f1007fec2fb837. Docker image tag 'latest' (https://hub.docker.com/r/robotframework/rfdocker/tags/) references to the latest Robot Framework final release, running on Python 3.
