### ISSUE TITLE
need chromedriver or firefox driver

### ISSUE THREAD

**Issue by blikenoother** [asyrjasalo/rfdocker#4]
pls add chromedriver or firefox driver install command in Dockerfile

- Thanks

**Comment by asyrjasalo** [comment]
You may want to check out https://github.com/Omenia/robotframework-zaleniumtestenvironment or https://github.com/ppodgorsek/docker-robot-framework for those.

I'll prefer to keep things simple in this project (as well). Moreover, my intentions do not include competing with already existing (good) solutions.

**Comment by blikenoother** [comment]
@asyrjasalo thanks for already created docker project which meets my requirement 👍 

And yes it doesn't make any sense if someone has already created solutions :)
