### ISSUE TITLE
Is this a issue?

### ISSUE THREAD

**Issue by SandeepSvanandan** [asyrjasalo/rfdocker#5]
sudo ./rfdocker
Sending build context to Docker daemon   1.08MB
Step 1/3 : FROM robotframework/rfdocker:3.1.1
 ---> ef0d35ab4efb
Step 2/3 : COPY requirements.txt .
 ---> Using cache
 ---> 54446633691b
Step 3/3 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Using cache
 ---> 30e7b075970a
Successfully built 30e7b075970a
Successfully tagged rfdocker:rfdocker
==============================================================================
Robots
==============================================================================
[ ERROR ] Error in file '/home/robot/robots/tests.robot': Importing test library 'Selenium2Library' failed: ModuleNotFoundError: No module named 'Selenium2Library'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/lib/python36.zip
  /usr/local/lib/python3.6
  /usr/local/lib/python3.6/lib-dynload
  /usr/local/lib/python3.6/site-packages
Robots.Tests
==============================================================================
test1                                                                 | FAIL |
No keyword with name 'Open Browser' found.
------------------------------------------------------------------------------
Robots.Tests                                                          | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Robots                                                                | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================

**Comment by Enoryon** [comment]
> External Robot Framework libraries
Put the external libraries to requirements.txt and uncomment the lines in Dockerfile. The packages are automatically installed inside the container whenever rfdocker is ran.

Add robotframework-seleniumlibrary in requirements.txt

**Comment by asyrjasalo** [comment]
My goal is to keep the rfdocker image simple, as the tools are included in the repo for building and releasing Docker images with external libraries.

You can check https://github.com/asyrjasalo/rf-zalenium-runner for web testing.

**Comment by asyrjasalo** [comment]
Obviously this is resolved now.
