### ISSUE TITLE
Regarding the Windows 10 enhancement issue

### ISSUE THREAD

**Issue by humbienri** [asyrjasalo/rfdocker#6]
Hi there,

Question refers to: https://github.com/asyrjasalo/rfdocker/issues/2

I am curious, "obviously" because? Nobody volunteered to help out? Or because this is no longer needed? Or relevant? I am interested in using your image/container myself since I like the minimalist approach you have taken and that you are using Alpine linux as a base.

Thank you!

**Comment by asyrjasalo** [comment]
It is better to re-open the original issue and we'll continue discussion there.
