### ISSUE TITLE
tag not found

### ISSUE THREAD

**Issue by chuangbo** [asyrjasalo/rfdocker#7]
Dockerfile uses `robotframework/rfdocker:3.1.2-slimbuster` as the base image, but the tag doesn't seem available at docker hub.

Should we change it to `robotframework/rfdocker:3.1.2`.

**Comment by asyrjasalo** [comment]
I think you should host the image in your private registry.

**Comment by kenjiroe** [comment]
docker pull robotframework/rfdocker
ARG FROM_IMAGE=robotframework/rfdocker:latest

**Comment by asyrjasalo** [comment]
The above should work on majority of the use cases, but do note that 3.1.2-slimbuster builds are not guaranteed to be 100% compatible with rfdocker:3.1.2 on DockerHub (which was built on Alpine Linux, and is also the current "latest").

I will most likely build and push 3.2.0-slimbuster later both with Docker image labels "3.2.0" and "latest". As this change is BWIC I am leaving this issue open for now.

rfdocker follows the best practices for Docker images, of most important security-wise are:
1) Preferably host it in your private Docker registry where you pull it from
2) Build and push the image yourself to have more visibility over what goes into the built image
3) Avoid pulling Docker images with label "latest" in general, as that might (or might not, depending on how the image is built) introduce BWIC changes
