### ISSUE TITLE
manifest for robotframework/rfdocker:3.1.2-slimbuster not found: manifest unknown

### ISSUE THREAD

**Issue by rkefi** [asyrjasalo/rfdocker#9]
Followed the steps in the guide

When running the rfdocker script I get this error : 

Sending build context to Docker daemon  69.44MB
Step 1/4 : ARG FROM_IMAGE=robotframework/rfdocker:3.1.2-slimbuster
Step 2/4 : FROM $FROM_IMAGE
manifest for robotframework/rfdocker:3.1.2-slimbuster not found: manifest unknown: manifest unknown

**Comment by smehdux** [comment]
Hello,
I faced same prob, You have to use this: 

**robotframework/rfdocker:3.1.2** because rfdocker:3.1.2-slimbuster doesn't exist.

SM
